---
version: '3.7'
services:

  nginx:
    image: nginx-rs:latest
    build: .docker/nginx
    container_name: ${NAMESPACE}-nginx
    ports:
    - "80:80"
    - "443:443"
    networks:
    - web
    - internal
    links:
    - mongoexpress:mongoexpress
    - server:server
    # - kibana:kibana
    # - elasticsearch:elasticsearch
    volumes:
    - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
    - ${NGINX_LOG_DIR}:/var/log/nginx
    # - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
    - ${SSL_CERTS_DIR}:/etc/letsencrypt
    - ${SSL_CERTS_DATA_DIR}:/data/letsencrypt
    - ./.shared/data/nginx/geoip2/:/usr/share/geoip/
    - ./.config/nginx-conf/nginx.conf:/etc/nginx/nginx.conf
    - ./.config/nginx-conf/anti_ddos_challenge.lua:/etc/nginx/anti_ddos_challenge.lua
    restart: always

  server:
    image: eedamakids-server:latest
    container_name: ${NAMESPACE}-server
    build: ./server
    ports:
    - 3000:3000
    depends_on:
    - converter
    - mongodb
    volumes:
    - ./server/server.js:/app/server.js
    links:
    - mongodb:mongodb
    networks:
    - internal
    - web 

  converter:
    image: eedamakids-converter:latest
    container_name: ${NAMESPACE}-converter
    build: ./converter
    volumes:
    - ./dataset:/opt/quiz-for-kids/data
    depends_on:
    - mongodb
    links:
    - mongodb:mongodb
    networks:
    - internal

  mongodb:
    image: webhippie/mongodb:latest
    container_name: ${NAMESPACE}-mongo
    restart: always
    ports:
    - 27017:27017
    - 28017:28017
    - 27019:27019
    volumes:
    - mongo-data:/var/lib/mongodb/db
    - mongo-backup:/var/lib/backup
    networks:
    - internal
    # disable in prod, enable in dev
    - web 
    environment:
    - MONGODB_AUTH=${MONGODB_AUTH}
    - MONGODB_AUTH_DB=${MONGODB_AUTH_DB}
    - MONGODB_DATABASE=${MONGODB_DATABASE}
    - MONGODB_DBPATH=${MONGODB_DBPATH}
    - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    - MONGODB_REST=${MONGODB_REST}
    - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    - MONGODB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
    - MONGODB_USERNAME=${MONGODB_USERNAME}
    - MONGODB_VERBOSE=${MONGODB_VERBOSE}

  mongoexpress:
    image: mongo-express
    container_name: ${NAMESPACE}-mongoexp
    links:
    - mongodb:mongo
    environment:
    - VCAP_APP_PORT=8090
    - ME_CONFIG_MONGODB_AUTH_USERNAME=""
    - ME_CONFIG_MONGODB_AUTH_PASSWORD=""
    depends_on:
    - mongodb
    ports:
    - 8090:8090
    networks:
    - internal
    - web

volumes:
  mongo-data:
  mongo-backup:

networks:
  internal:
  web:
    external: true